# Copyright (C) 2018-2020 Virto Solutions. All Rights Reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

services:

  vc-db:
    image: postgres:${PGSQL_VERSION:-16.9}
    ports:
      - "${DOCKER_SQL_PORT:-5432}:5432"
    expose:  
      - 5432  
    environment: 
      - POSTGRES_DB=VirtoCommerce3
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD:-v!rto_Labs!}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - virto

  # redis:
  #   image: redis:alpine
  #   command: redis-server --requirepass ${REDIS_PASSWORD:-v!rto_Labs!}
  #   ports:
  #     - "${REDIS_PORT:-6379}:6379"
  #   environment:
  #     - REDIS_REPLICATION_MODE=master
  #   volumes:
  #     - redisdata:/data
  #   networks:
  #     - virto

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION:-8.18.0}
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT:-9200}:9200
    networks:
      - virto
    environment:
      - node.name=es
      - cluster.name=${CLUSTER_NAME:-elasticsearch}
      - cluster.initial_master_nodes=es
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-v!rto_Labs!}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=${LICENSE:-basic}
      - xpack.ml.use_auto_machine_memory_percent=true
    restart: "on-failure"
    mem_limit: ${MEM_LIMIT:-1g}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:${ES_PORT:-9200}",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION:-8.18.0}
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    networks:
      - virto
    environment:
      - ELASTICSEARCH_HOSTS=http://es:${ES_PORT:-9200}
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD:-Kibana-v!rto_Labs!}
      - XPACK_SECURITY_ENABLED=false
    depends_on:
      - es
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:${KIBANA_PORT:-5601}/api/status",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  vc-platform-web:
    image: vc-platform:local-latest
    ports:
      - "${DOCKER_PLATFORM_PORT:-8090}:80"
    environment:
      - ASPNETCORE_URLS=http://+
      - VirtoCommerce:AllowInsecureHttp=true
      - VirtoCommerce:Hangfire:JobStorageType=Memory
      - DatabaseProvider=PostgreSql
      - ConnectionStrings:VirtoCommerce=User ID=postgres;Password=${DB_PASSWORD:-v!rto_Labs!};Host=vc-db;Port=5432;Database=VirtoCommerce3
      - Assets:FileSystem:PublicUrl=http://localhost:${DOCKER_PLATFORM_PORT:-8090}/assets/
      - Content:FileSystem:PublicUrl=http://localhost:${DOCKER_PLATFORM_PORT:-8090}/cms-content/
      - Search:Provider=ElasticSearch8
      - Search:ElasticSearch8:Server=http://es:${ES_PORT:-9200}
      - Search:ElasticSearch8:User=elastic
      - Search:ElasticSearch8:Key=${ELASTIC_PASSWORD:-v!rto_Labs!}
      - Search:ElasticSearch8:EnableCompatibilityMode=true
    depends_on:
      - vc-db
      - es
      # - redis
    entrypoint: ["/wait-for-it.sh", "vc-db:5432", "-t", "120", "--", "dotnet", "VirtoCommerce.Platform.Web.dll"]
    volumes:
      - cms-content-volume:/opt/virtocommerce/platform/wwwroot/cms-content
      - modules-volume:/opt/virtocommerce/platform/modules
    networks:
      - virto
    restart: unless-stopped

volumes:
  cms-content-volume:
    name: cms-content-data
  modules-volume:
    name: modules-data
  postgres_data:
    driver: local
  esdata01:
    driver: local
  # redisdata:
  #   driver: local

networks:
  virto:
